name: nginx webserver

on:
  push:
    branches: 
         - '*'
jobs:
   env_setup:
       runs-on: self-hosted
       steps:
          - name: Install nginx webserver
            run: |
                 sudo amazon-linux-extras install nginx1 -y
   build:
       runs-on: self-hosted 
       needs: env_setup
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Cloning the repo"
               ls -lh
               sudo cp -r index.html /usr/share/nginx/html/
               sudo systemctl restart nginx
